module.exports = {
    APPLICATION_ID: "6FB6Ld2OzMVEUt9sZmrTy2zcjgXoQWlOeVBL4Vbs",
    JAVASCRIPT_KEY: "61PKELuE0IaHYYSehNKjS7pL2h2Y8UNCZpTWoNLO",
    SERVER_URL: "https://parseapi.back4app.com/",
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_test_51MAJiYKbYARSgHwe0QtTN7ELoFhRCPmO0ClOwHB0e8zLjAI1DI6OCmpMEl8zkIuU3S7EQjgIBuSTHDsDo76hK06L00dzYpoHXL',
    NEXT_PUBLIC_STRIPE_PRICE_ID: 'price_1MAJnNKbYARSgHwethdxG7FS'
  };